version: '3.8'

services:
  backend:
    build: ./backend
    container_name: hirenest-backend
    env_file:
      - ./backend/.env
    ports:
      - "5002:5002"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: hirenest-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    restart: unless-stopped
